# -*- coding: utf-8 -*-
"""Chatbot_NLP_Industrial_Safety.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wXgq7NfZQoIXafQ9QAMNaxAO2q4fqMV6

##This is a project on classifying the message recieved through a chatbot into severity categories for proper judgement of the accident scenarios.

## Importing the required Libraries
"""

!pip install kaggle

!pip install nlpaug

!pip install torch

!pip install torchtext

!pip install unidecode

!pip install autocorrect

!pip install --upgrade tensorflow

# Commented out IPython magic to ensure Python compatibility.
import zipfile as zf
import pandas as pd
import numpy as np
import datetime as dt
import re
import string
import spacy
import tensorflow as tf
import torch

import matplotlib.pyplot as plt
# %matplotlib inline
from matplotlib.ticker import MaxNLocator
import seaborn as sns
from statsmodels.graphics.mosaicplot import mosaic
from scipy.sparse import vstack

from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score
from imblearn.over_sampling import SMOTE

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.util import ngrams
from nltk import pos_tag
from collections import Counter
from gensim.models import Word2Vec

from keras.models import Model, Sequential
from keras.optimizers import Adam
from keras.layers import Input, Embedding, LSTM, Dense, concatenate, SimpleRNN, Bidirectional
from keras.regularizers import l2
from keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

import unicodedata
from unidecode import unidecode
from autocorrect import Speller
from string import punctuation
from wordcloud import WordCloud, STOPWORDS

import nlpaug.augmenter.word as naw
from nlpaug.util import Action
from transformers import pipeline
import torchtext.utils as utils
import torchtext.vocab as vocab

import warnings
warnings.filterwarnings("ignore")

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')

"""### **PROBLEM CONTEXT:**
##### The database comes from one of the biggest industry in Brazil and in the world. It is an urgent need for industries/companies around the globe to understand why employees still suffer some injuries/accidents in plants. Sometimes they also die in such environment.

### **DATA DESCRIPTION:**
##### This The database is basically records of accidents from 12 different plants in 03 different countries which every line in the data is an occurrence of an accident.
##### Columns description:
<ul>
    <li>Data: timestamp or time/date information</li>
    <li>Countries: which country the accident occurred (anonymised)</li>
    <li>Local: the city where the manufacturing plant is located (anonymised)</li>
    <li>Industry sector: which sector the plant belongs to</li>
    <li>Accident level: from I to VI, it registers how severe was the accident (I means not severe but VI means very severe)</li>
    <li>Potential Accident Level: Depending on the Accident Level, the database also registers how severe the accident could have been (due to other factors involved in the accident)</li>
    <li>Genre: if the person is male of female</li>
    <li>Employee or Third Party: if the injured person is an employee or a third party</li>
    <li>Critical Risk: some description of the risk involved in the accident</li>
    <li>Description: Detailed description of how the accident happened.</li>
</ul>

### **PROJECT OBJECTIVE**
##### Design a ML/DL based chatbot utility which can help the professionals to highlight the safety risk as per the incident description.

## MILESTONE 1
### Step 1: Import the data
"""

!kaggle datasets download -d ihmstefanini/industrial-safety-and-health-analytics-database

folder = '/content/'

data = pd.read_csv(folder + 'Industrial_Safety_Data.csv')
pd.set_option('display.max_colwidth', None)

data.head()

data.info()

data.shape

"""### Step 2: Data cleansing"""

data.isna().sum()

# Remove the duplicate records in the data

print('There are ', data.shape[0], 'records and ', data.duplicated().sum(), ' duplicates in this dataset.')
data = data.drop_duplicates()
print('There are ', data.shape[0], 'records and ', data.duplicated().sum(), ' duplicates in this dataset.')

# Remove the first 'Unnamed' column
data.drop(data.columns[0], axis=1, inplace=True)

# Renaming the columns appropriately
data.rename(columns={'Data':'Date', 'Countries':'Country', 'Local':'City', 'Genre':'Gender', 'Employee or Third Party':'Employee Type'}, inplace=True)

# Extracting year & month from 'Data' column
data['Date'] = pd.to_datetime(data['Date'], format='%d-%m-%Y %H:%M')
data['Year'] = data['Date'].dt.year
data['Month'] = data['Date'].dt.month
data['Day'] = data['Date'].dt.day_name()

data.info()

data.head()

# Checking the unique values of each column
col_ls = data.columns[:data.shape[1]-1]

for col in col_ls:
    print("\n", col, ":")
    print(data[col].unique())

data[data['Critical Risk']=='\nNot applicable'].head()

temp = data
temp['Critical Risk'] = temp['Critical Risk'].str.replace(r'\nNot applicable', 'Not applicable', regex=True)

temp[temp['Critical Risk']=='Not applicable'].head()

col_ls = data.columns[:data.shape[1]-1]

for col in col_ls:
    print("\n\n", col, ":")
    print("----------------------------------------------------------------------------")
    print(data[col].unique())

"""### Exploratory Data Analysis

##### UNIVARIATE ANALYSIS
"""

def plot_uni(df, col, title):
    idx = df[col].value_counts().index
    plt.figure(figsize=(12,10))
    plt.subplot(2, 2, 1)
    plt.pie(df[col].value_counts(), autopct='%.1f', labels=idx, explode=[0.1]*len(idx))
    plt.title(title)
    plt.show()

plot_uni(data, 'Year', '% of accidents by Year')

"""Since the data is available only until 9th July 2017, the numbers above do not provide enough evidence to confirm if accidents increased/ decreased in 2017.

Now, comparing the first half of both years, we can see that the accidents reduced by about 20% in 2017.
"""

fig, axes = plt.subplots(1, 2, figsize=(9, 4), sharey=True)
# plt.subplot(1, 2, 2)
sns.countplot(data=data[data['Year']==2016], x='Month', palette='pastel', ax=axes[0])
axes[0].set_title('% of accidents by Month for 2016')
# plt.subplot(2, 2, 2)
sns.countplot(data=data[data['Year']==2017], x='Month', palette='pastel', ax=axes[1])
axes[1].set_title('% of accidents by Month for 2017')
plt.show()

"""You can see for each month from Feb - Jun, the number of accidents have reduced in 2017."""

fig, axes = plt.subplots(1, 2, figsize=(12, 7), sharey=True)
day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
data_16 = data[data['Year']==2016]
data_17 = data[data['Year']==2017]

sns.countplot(data=data_16, x='Day', order=day_order, palette='pastel', ax=axes[0])
axes[0].set_xticklabels(axes[0].get_xticklabels(), rotation=90)
total = sum(data_16['Day'].value_counts())
for p in axes[0].patches:
    axes[0].annotate('{:.1f}'.format(100 * p.get_height() / total),
                (p.get_x(), p.get_height()), size=9, xytext=(10, 10), textcoords='offset points')
axes[0].set_title('% of accidents by Day of the Week for 2016')

sns.countplot(data=data_17, x='Day', order=day_order, palette='pastel', ax=axes[1])
axes[1].set_xticklabels(axes[1].get_xticklabels(), rotation=90)
total = sum(data_17['Day'].value_counts())
for p in axes[1].patches:
    axes[1].annotate('{:.1f}'.format(100 * p.get_height() / total),
                (p.get_x(), p.get_height()), size=9, xytext=(10, 10), textcoords='offset points')
axes[1].set_title('% of accidents by Day of the Week for 2017')
plt.show()

"""For Both 2016 & 2017, about 70-80% accidents have happened during the weekdays. People travelling for work on weekdays could be the possible reason for this."""

plot_uni(data, 'Industry Sector', '% of accidents by Industry')

"""Mining industry witnesses the highest number of accidents, followed by Metals industry"""

plot_uni(data, 'Country', '% of accidents by Country')

"""Country_01 witnesses the highest number of accidents, followed by Country02, which together contribute to ~90% of the total accidents."""

plt.figure(figsize=(10, 5))
ax = sns.countplot(data, x='City', order=data['City'].value_counts().index)
sns.lineplot(data['City'].value_counts().values)
plt.xticks(rotation=90)
total = sum(data['City'].value_counts())
for p in ax.patches:
    ax.annotate('{:.1f}'.format(100 * p.get_height() / total),
                (p.get_x(), p.get_height()), size=9, xytext=(10, 10), textcoords='offset points')
plt.title('% of accidents by City')
plt.show()

"""About 61% of the accidents together occur in plants located in Local_01, Local_03, Local_04 & Local_05 cities, of which Local_03 alone has recorded 21% accidents. Another 21% accidents are recorded by Local_06 & Local_10 cities. The bottom most 6 cities - Local_02, Local_07, Local_08, Local_09, Local_11, Local_12 cities witnessed only 17% of the accidents."""

plot_uni(data, 'Gender', '% of accidents by Gender')

"""We can see the only ~5% Females have encountered accidents. This could be due to a general assumption of majority of industrial jobs being taken up by Males."""

plot_uni(data, 'Employee Type', '% of accidents by Employee Type')

"""The minimum accidents are faced by the Third Party Remote workers as they are not always working on the sites. Overall 58% of the accidents are encountered Third Party employees."""

plt.figure(figsize=(10, 5))
sns.countplot(data, x='Critical Risk')
plt.xticks(rotation=90)
plt.show()

"""Most of the risks are grouped under Others which is about 50% of the dataset. The more common risks observed in the accidents are: Pressed, Manual Tools, Chemical Substances, Venomous Animals, Projection & Cut."""

plot_uni(data, 'Accident Level', '% of accidents by Accident Level')

plot_uni(data, 'Potential Accident Level', '% of accidents by Potential Accident Level')

"""<b>Observations:</b><br/>
<ol>
    <li>Accident Level: Majority of the accidents fall under Level I occuring due to minor misses, while Level II, III & IV have similar frequency of occurence. High risk or severe accidents under Level V are only 2%.</li>
    <li>Potential Accident Level: 81% accidents could potentially be moderately severe onces. and only 7.5% could've potentially been the most severe ones.</li>
    <li>Potential Accident Level differs from the Accident Level. Majority are Level I accidents wheareas potential accidents have a majority in moderately severe ones (Level II, III & IV together).</li>
    <li>Potential Accident Level: It has 6 Accident levels where the Level VI has only 1 accident recorded. To simplify and be able to compare the Accident & Potential Accident Level, we can change this record to the closest level V.</li>
</ol>
"""

# Changing Accident Level VI to closest Level V
data['Potential Accident Level'].replace('VI', 'V', inplace=True)
data[data['Potential Accident Level']=='VI']

"""##### MULTIVARIATE ANALYSIS"""

labenc = LabelEncoder()
df = data.iloc[:,1:].apply(labenc.fit_transform)

plt.figure(figsize=(12, 12))
plt.title('Correlation Matrix of all variables')
sns.heatmap(df.corr(), annot=True, square=True)

"""<b>Observations:</b><br/>
<ol>
    <li>The highest correlation is seen between City & Country, which is also the most obvious expectation.</li>
    <li>Accident Level & Potential Accident Level have only 50% correlation.</li>
    <li>There is only low to moderate correlation among the other variables.</li>
</ol>
"""

fig, axes = plt.subplots(figsize=(15, 10))
marker_styles = {'Mining':'o', 'Metals':'h', 'Others':'s'}
size_order = list(data['Potential Accident Level'].sort_values(ascending=True).unique())
sns.scatterplot(data=data, y='Accident Level', x='Critical Risk', hue='Industry Sector',
                style='Industry Sector', markers=marker_styles,
                size='Potential Accident Level', size_order=size_order, ax=axes, sizes=(100, 1000), palette='tab20')
axes.set_title('Accident Level v/s Potential Accident Level, Critical Risk & Industry Sector')
axes.legend(loc='upper left', bbox_to_anchor=(1, 1))
plt.xticks(rotation=90)
plt.show()

"""<b>Observations:</b><br/>
<ol>
    <li>Most of the accidents occured are the least severe ones (level I), and majority of them could've potentially been more severe as Levels II & III accidents.</li>
    <li>The most common risk seen in all industries is related to Fall - Fall & Fall Prevention.</li>
    <li>All the most severe accidents (level V) are also potentially the most severe accidents, and all the risks associated are seen in Mining industry, except 'Power Lock' which is observed as a critical risk for these accidents in Metals industry.</li>
    <li>Some of the level I accidents in Mining industry could have been level IV accidents potentially, with different risks like Electrical Installation, Projection & Power Lock. </li>
    <li>All the Level IV accidents are also marked as potentially Level IV accidents only, except accidents caused to risks of Elecrtrical Installation, Projection, Burn & one accident with no risks (Not Applicable).</li>
    <li>The following risks are only seen in Metals industry: Pressurized Systems, Liquid Metal, Confined Space, Chemicals Substances, Blocking and isolation of engines, Suspended Loads, Burn, Machine Protection, with majority of them observed in Level I accidents.</li>
    <li>Majority of Level II accidents could've potentially been Level III & IV accidents, except the ones with the risks associated in the 'Others' category.</li>
</ol>
"""

def plot_bi(df, col, huecol, title, ax):
    ax = sns.countplot(data, x=col, order=data[col].value_counts().index, hue=huecol, ax=ax)
    total = len(data[col])
    for p in ax.patches:
        ht = p.get_height()
        ax.annotate(f'{ht}\n({ht / total: .1%})',
                    (p.get_x() + p.get_width() / 2., ht), ha='center', va='center',
                    size=9, xytext=(0, 3), textcoords='offset points')
    ax.set_title(title)
    return ax

"""Understanding Country-City mapping first"""

data[['Country', 'City']].drop_duplicates().sort_values(['Country', 'City']).reset_index(drop=True)

figure, axes = plt.subplots(1, 1, figsize=(10, 5))
plot_bi(data, 'Country', 'Accident Level', 'Accident Level by Country', axes)
plt.show()

plt.figure(figsize=(12, 5))
ax = sns.countplot(data, x='City', order=data['City'].value_counts().index, hue='Accident Level')
ax.set_xticklabels(ax.get_xticklabels(), rotation=90)
for p in ax.patches:
    ax.annotate('{:.0f}'.format(p.get_height()),
                (p.get_x(), p.get_height()), size=9, xytext=(3, 3), textcoords='offset points')
ax.set_title('Accident Level by City')
plt.show()

plt.figure(figsize=(12, 20))
sns.countplot(data, y='Critical Risk', order=data['Critical Risk'].value_counts().index, hue='Accident Level')
plt.title('Accident Level by Critical Risk')
plt.show()

"""<b>Observations:</b><br/>
<ol>
    <li>Country_01 witnesses the maximum accidents with a majority of low severity ones (Level I).</li>
    <li>68% of the moderately severe accidents (Levels II, II, IV) have occurred in Local_03 & Local_04 cities.</li>
    <li>Local_9, Local_11, Local_12 cities have only 2-4 accidents, could be due to low population or low staff in these plants, but we do not have any data to confirm that.</li>
    <li>Although country_02 has maximum number of plants but witnesses 2nd highest number of accidents, majority of which being least severity accidents (Level I).</li>
    <li>Plants in Local_01, Local_03, Local_04, & Local_06 cities only have faced the highest severity accidents (Level V). The risks associated could be Fall, Vehicles & Mobile Equipment, Remains of Choco & Power Lock and some are categorized under 'Others'.</li>
    <li>Most of the risks have contributed to least severe accidents of Level I, majority of which are recorded in Country_01.</li>
    <li>Risks like Cut, Chemical Substances, Manual Tools, Pressed, Projection are the causes of moderate severity accidents (Level II, II & IV)</li>
</ol>
"""

figure, axes = plt.subplots(1, 1, figsize=(10, 5))
plot_bi(data, 'Industry Sector', 'Accident Level', 'Accident Level by Industry Sector', axes)
plt.show()

"""<b>Observations:</b><br/>
<ol>
    <li>The most severe accidents (level V) are seen only in Mining & Metals industry sectors, where only 1 has occured in Metals industry & the rest in Mining industry.</li>
    <li>The 'Others' industry sector has least accidents, with majority being the least severe ones (level I).</li>
    <li>Accident Levels III & IV are almost equally distribute in Mining & Metals industry, while Level II accidents have occured more in both.</li>
</ol>
"""

fig, axes = plt.subplots(2, 2, figsize=(16, 10))

plot_bi(data, 'Gender', 'Accident Level', 'Accident Level by Gender', axes[0, 0])
plot_bi(data, 'Gender', 'Industry Sector', 'Industry Sector by Gender', axes[0, 1])
plot_bi(data, 'Gender', 'Employee Type', 'Employee Type by Gender', axes[1, 0])
plot_bi(data, 'Gender', 'Country', 'Country by Gender', axes[1, 1])

plt.tight_layout()
plt.show()

"""<b>Observations:</b><br/>
<ol>
    <li>There are no females suffered from an accident in Country_03, but even in other 2 countries together, only 6% of the accidents have females involved.</li>
    <li>About 60% of the females met with accident in Metals industry, and 23% in Mining industry, while the rest in 'Others'.</li>
    <li>There is almost equal distribution of females as different types of employees.</li>
    <li>82% of the females were involved in least severity accidents (Level I) and the rest in moderate severity ones (levels II, III, IV).</li>
    <li>87% of the men, with almost equal distribution, are either direct Employees or Third Party employees.</li>
    <li>As the accident of level I have occured more, 74% of men have met with them, but only 2% of men have suffered from most severe accidents (Level V), with no women involved in these.</li>
</ol>
"""

count = pd.crosstab(columns=data['Accident Level'], index=data['Month'])
ax = count.plot(kind='bar', stacked=True, figsize=(13, 6))
ax.set_title('Accident Levels by Month')
ax.set_ylabel('count')

count = pd.crosstab(columns=data['Accident Level'], index=data['Day'])
ax = count.plot(kind='bar', stacked=True, figsize=(13, 6))
ax.set_title('Accident Levels by Day')
ax.set_ylabel('count')

"""<b>Observations:</b><br/>
<ol>
    <li>Majority of potentially high severity accidents (level V) are seen in the month of March and especially on Wednesdays & Saturdays of the week.</li>
    <li>Majority of moderate severity accidents (levels II, III, IV) are seen in February & March.</li>
    <li>Majority of potentially least severe accidents (level I) are seen in first half of the year. But these numbers don't include data post 9th July 2017, hence this does not provide a full view.</li>
	<li>Monday has witnessed only Level I, II & II accidents, while Level IV accidents have mostly occured on Tuesday, Thursday, Friday & Sunday.</li>
</ol>

### Step 3: Data preprocessing (NLP Preprocessing techniques)

We will work on the Description column here, which will help us identify the real causes of these accidents.
"""

pp_data = data.copy()
pp_data['Description'].head()

# Checking if there are any UTF-8 characters
def check_beyond_ascii(text):
    return all(ord(char) > 128 for char in text)

pp_data['Has_outside_ASCII'] = pp_data['Description'].apply(check_beyond_ascii)

if((pp_data['Has_outside_ASCII'].unique()[0]==False) | (len(pp_data['Has_outside_ASCII'].unique())==2)):
    print(pp_data['Has_outside_ASCII'].unique(), ': There are no characters beyond the range of ASCII character set.')
else:
    print(pp_data['Has_outside_ASCII'].unique(), ': There are characters beyond the range of ASCII character set. Please remove them.')
pp_data.drop('Has_outside_ASCII', axis=1, inplace=True)

# Checking if there are any HTML tags or URLs
def check_html_urls(text):
    check_pattern = re.compile(r'https?://\S+|www\.\S+|<[^>]+>')
    return bool(check_pattern.search(text))

# Assuming pp_data is a DataFrame with a 'Description' column
pp_data['Has_HTML_URLs'] = pp_data['Description'].apply(check_html_urls)
if((pp_data['Has_HTML_URLs'].unique()[0]==False) | (len(pp_data['Has_HTML_URLs'].unique())==2)):
    print(pp_data['Has_HTML_URLs'].unique(), ': There are no HTML tags or URLs in the data.')
else:
    print(pp_data['Has_HTML_URLs'].unique(), ': There are HTML tags or URLs in the data. Please remove them.')
pp_data.drop('Has_HTML_URLs', axis=1, inplace=True)

"""There are no characters beyond ASCII character set range and no HTML tags or URLs in the dataset. <br/>
The numbers in the text are used for measurements, time, etc. hence provide meaningful information, but will not be helpful during vectorization and modelling, as it would add more noise and sparsity. Hence, we decided to retain only alphabetic characters.

##### PRE-PROCESSING FUNCTION
"""

def pre_processing(text):
    # Lowercasing the entire text
    text = text.lower()

    # Dealing with accented characters and unicodes by using Unicode normalization
    text = unidecode(text)
    text = unicodedata.normalize('NFKD', text)

    # Retaining only alphabetic characters
    text = ' '.join(re.compile(r'[a-z]+').findall(text))

    # Removing English Stopwords
    stopwords_list = set(stopwords.words('english'))
    text = ' '.join([word for word in word_tokenize(text) if word not in stopwords_list])

    # Lemmatizing the text now
    lemmatizer = WordNetLemmatizer()
    text = ' '.join([lemmatizer.lemmatize(word) for word in word_tokenize(text)])

    return text

pp_data['Description'] = pp_data['Description'].apply(pre_processing)

pp_data['Description'].head()

descriptions = ' '.join(pp_data['Description'])
descriptions = ' '.join([word for word in descriptions.split()])

descriptions_wc = WordCloud(stopwords=STOPWORDS, colormap='RdBu', background_color='white',
                            width=3000, height=2500).generate(descriptions)

plt.figure(figsize=(20, 20))
plt.subplot(1, 2, 1)
plt.imshow(descriptions_wc, interpolation='bilinear')
plt.axis('off')
plt.title('Accident Description Word Cloud')

"""Let's perform POS tagging to verify this.

##### POS TAGGING
"""

description_list = pp_data['Description'].tolist()
pos_tags = [pos_tag(word_tokenize(desc)) for desc in description_list]
pp_data['POS_Tags'] = pos_tags

# Flatten the list of POS tags
flat_pos_tags = [tag[0] for sublist in pos_tags for _, tag in sublist]

# Get all nouns and verbs
nouns = [word for word, tag in zip(word_tokenize(" ".join(description_list)), flat_pos_tags) if tag.startswith('N')]
verbs = [word for word, tag in zip(word_tokenize(" ".join(description_list)), flat_pos_tags) if tag.startswith('V')]

# Create WordCloud for Nouns
noun_wc = WordCloud(width=800, height=400, background_color='white').generate(" ".join(nouns))
plt.figure(figsize=(10, 5))
plt.imshow(noun_wc, interpolation='bilinear')
plt.axis('off')
plt.title('Word Cloud for Nouns')
plt.show()

# Create WordCloud for Verbs
verb_wc = WordCloud(width=800, height=400, background_color='white').generate(" ".join(verbs))
plt.figure(figsize=(10, 5))
plt.imshow(verb_wc, interpolation='bilinear')
plt.axis('off')
plt.title('Word Cloud for Verbs')
plt.show()

"""<b>Observations:</b><br/>
<ol>
    <li>There are a lot of action words like: falling, cutting, drilling, hitting, cleaning, slipped, injured, carried, moving, pressing, etc. These actions must have led to the accident.</li>
    <li>There are a lot of nouns which can also help us understand the object causing the accident, like: truck, pipe, bee, vehicle, tube, floor, support mesh, ladder, helmet, metal, bolt, rock, water, tool, sting, equipment, etc.</li>
</ol>
"""

pp_data.head()

"""### Step 4: Data preparation - Cleansed data in .xlsx or .csv file

##### TOKENIZATION
"""

# Using SpaCy for Tokenization
spacy_eng = spacy.load('en_core_web_sm')
pp_data['Description'] = pp_data['Description'].astype(str)
pp_data['Tokenized Text'] = pp_data['Description'].apply(lambda x: [token.text for token in spacy_eng(x)])
pp_data.head()

"""##### N-GRAMS"""

# Finding n-grams for the Description
def generate_ngrams(text, n):
    doc = spacy_eng(text)
    ngrams = list(zip(*[doc[i:] for i in range (n)]))
    return [' '.join(tokens.text for tokens in ng) for ng in ngrams]

pp_data['Uni-grams'] = pp_data['Description'].apply(lambda x: generate_ngrams(x, 1))
pp_data['Bi-grams'] = pp_data['Description'].apply(lambda x: generate_ngrams(x, 2))
pp_data['Tri-grams'] = pp_data['Description'].apply(lambda x: generate_ngrams(x, 3))

pp_data.head()

# Let's find the most frequent n-grams
unigm = [ng for sublist in pp_data['Uni-grams'] for ng in sublist]
bigm = [ng for sublist in pp_data['Bi-grams'] for ng in sublist]
trigm = [ng for sublist in pp_data['Tri-grams'] for ng in sublist]

freq_unigm = pd.DataFrame(Counter(unigm).most_common(), columns=['Uni-gram', 'Frequency'])
freq_bigm = pd.DataFrame(Counter(bigm).most_common(), columns=['Bi-gram', 'Frequency'])
freq_trigm = pd.DataFrame(Counter(trigm).most_common(), columns=['Tri-gram', 'Frequency'])

print('Most frequent Uni-grams: \n', freq_unigm.head(20))
print('Most frequent Bi-grams: \n', freq_bigm.head(20))
print('Most frequent Tri-grams: \n', freq_trigm.head(20))

"""The most frequent Bi-grams provide useful information regarding the cause of accident, while the unigrams seem to get covered in bi-grams and the tri-grams do not seem to be adding any useful information on top of bi-grams. For Example: 'injury', 'causing injury' & 'causing injury described'. Hence, we can use the range of only 2 during vector encodings.

##### SAVING THE PRE-PROCESSED DATA FILE IN .CSV FORMAT
"""

output_path = str(folder + 'IHMStefanini_industrial_safety_and_health_cleansed.csv')
pp_data.to_csv(output_path, index=False)

"""##### VECTOR ENCODING VIA TF-IDF"""

tfidf_vectorizer = TfidfVectorizer(max_features=1000, stop_words='english', ngram_range=(2, 2))
tfidf_matrix = tfidf_vectorizer.fit_transform(description_list)
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=tfidf_vectorizer.get_feature_names_out())

tfidf_df.head()

tfidf_df.shape

# Display the most important features
tfidf_scores = tfidf_df.sum(axis=0)
tfidf_scores_df = pd.DataFrame({'Feature': tfidf_vectorizer.get_feature_names_out(), 'TF-IDF Score': tfidf_scores})

top_features = tfidf_scores_df.sort_values(by='TF-IDF Score', ascending=False)

print("Top Features:")
print(top_features.head(30))

"""You can see most of the accidents are related to injuries on hands, fingers, feet, legs.

##### VECTOR ENCODING VIA WORD2VEC
"""

tokens_list = pp_data['Tokenized Text'].to_list()
word2vec_vectorizer = Word2Vec(sentences=tokens_list, vector_size=1000, window=5, min_count=1, workers=4)

def get_sentence_vector(sentence, vectorizer):
    vector_sum = 0
    for word in sentence:
        if word in vectorizer.wv:
            vector_sum += vectorizer.wv[word]
    return vector_sum

pp_data['Description_Vector'] = [get_sentence_vector(sentence, word2vec_vectorizer) for sentence in tokens_list]

pp_data[['Description', 'Description_Vector']]

"""### Step 5: Design train and test basic machine learning classifiers"""

# Assigning the target vairable for modelling
Y = pp_data['Accident Level']

"""##### MODELLING USING TF-IDF VECTORS"""

# Splitting Training & Testing data
X_tf = tfidf_matrix

x_train_tf, x_test_tf, y_train, y_test = train_test_split(X_tf, Y, test_size=0.3, random_state=42, stratify=Y)

# Creating function for 5 different ML classifiers
def ml_classfiers(x_train, x_test, y_train, y_test):
    classifiers_dict = {
        'Logistic Regression': LogisticRegression(random_state=42),
        'Random Forest': RandomForestClassifier(n_estimators=100, max_depth=6),
        'K-Nearest Neighbor': KNeighborsClassifier(n_neighbors=50),
        'Support Vector Machine': SVC(kernel='rbf', C=1.0),
        'AdaBoost': AdaBoostClassifier(n_estimators=50, random_state=42)
    }

    classfier_list = []
    accuracy_scores = []
    precision_scores = []
    recall_scores = []
    f1_scores = []

    # Evaluate Model Performance
    for name, classifer in classifiers_dict.items():
        clf = classifer.fit(x_train, y_train)
        y_pred = classifer.predict(x_test)
        accuracy = float(accuracy_score(y_test, y_pred)) * 100
        report = classification_report(y_test, y_pred)
        conf_mx = confusion_matrix(y_test, y_pred)
        precision = float(report.split('\n')[-2].split()[2]) * 100
        recall = float(report.split('\n')[-2].split()[3]) * 100
        f1_score = float(report.split('\n')[-2].split()[4]) * 100
        classfier_list.append(name)
        accuracy_scores.append(accuracy)
        precision_scores.append(precision)
        recall_scores.append(recall)
        f1_scores.append(f1_score)
        print(name, ': \n')
        print('-----------------------------------------------------------------')
        print('Classification Report: \n', report)
        print('Confusion Matrix: \n', conf_mx)

    # Create Performance Dataframe
    classifiers_df = pd.DataFrame({'Name':classfier_list, 'Accuracy (in %)': accuracy_scores,
                                   'Precision (in %)': precision_scores, 'Recall (in %)': recall_scores,
                                   'F1-Score (in %)': f1_scores})
    return classifiers_df

ml_classfiers_results_tfidf = ml_classfiers(x_train_tf, x_test_tf, y_train, y_test)

print('For models built on TF-IDF vectors:')
ml_classfiers_results_tfidf

"""<b>Observations:</b><br/>
<ol>
    <li>All the models, excpet AdaBoost, are providing the same accuracy of 74%, ~2% higher than AdaBoost. But for such a highly imbalanced dataset, it's better to use weighted average of Precision, Recall & F1-Score as performance metrics.</li>
    <li>All the models provide very low performance, with only 55% Precision & 62-63% F1-Score, as only accidents of Level I have been correctly predicted and all the accidents in Level II - V are incorrectly predicted as Level I.</li>
    <li>This is due to the dataset being small and highly imbalanced with majority of the accidents from Level I.</li>
</ol>

##### MODELLING USING WORD2VEC VECTORS
"""

# Splitting Training & Testing data
X_wv = pp_data['Description_Vector'].to_list()

x_train_wv, x_test_wv, y_train, y_test = train_test_split(X_wv, Y, test_size=0.3, random_state=42, stratify=Y)

ml_classfiers_results_wv = ml_classfiers(x_train_wv, x_test_wv, y_train, y_test)

print('For models built on Word2Vec vectors:')
ml_classfiers_results_wv

"""You can observe that there is no difference in the model performance on both the Vectorization methods: TF-IDF & Word2Vec. Hence, going forward we can choose either one, we're selecting TF-TDF here as the importance of the words in a sentence matters to understand the cause of the accident and identify the Accident Level.

##### MODEL PERFORMANCE TUNING USING GRID SEARCH
"""

# Creating function for 5 different ML classifiers
def ml_classfiers_with_grid_search(x_train, x_test, y_train, y_test):
    classifiers_dict = {
        'Logistic Regression': LogisticRegression(random_state=42),
        'Random Forest': RandomForestClassifier(),
        'K-Nearest Neighbor': KNeighborsClassifier(),
        'Support Vector Machine': SVC(kernel='rbf'),
        'AdaBoost': AdaBoostClassifier(random_state=42)
    }

    param_grid = {
        'Logistic Regression': {'C': [0.001, 0.01, 0.1, 1, 10, 100]},
        'Random Forest': {'n_estimators': [50, 100, 150], 'max_depth': [5, 10, 15]},
        'K-Nearest Neighbor': {'n_neighbors': [5, 10, 15, 20, 25]},
        'Support Vector Machine': {'C': [0.1, 1, 10, 100], 'gamma': ['scale', 'auto']},
        'AdaBoost': {'n_estimators': [20, 50, 100], 'learning_rate': [0.01, 0.1, 1]}
    }

    classfier_list = []
    accuracy_scores = []
    precision_scores = []
    recall_scores = []
    f1_scores = []

    for name, classifer in classifiers_dict.items():
        # Perform Grid Search
        grid_search = GridSearchCV(classifer, param_grid[name], scoring='accuracy', cv=5)
        grid_search.fit(x_train, y_train)
        best_model = grid_search.best_estimator_

        # Evaluate the Best Model
        y_pred = best_model.predict(x_test)
        accuracy = float(accuracy_score(y_test, y_pred)) * 100
        report = classification_report(y_test, y_pred)
        conf_mx = confusion_matrix(y_test, y_pred)
        precision = float(report.split('\n')[-2].split()[2]) * 100
        recall = float(report.split('\n')[-2].split()[3]) * 100
        f1_score = float(report.split('\n')[-2].split()[4]) * 100
        classfier_list.append(name)
        accuracy_scores.append(accuracy)
        precision_scores.append(precision)
        recall_scores.append(recall)
        f1_scores.append(f1_score)
        print(name, ': \n')
        print('-----------------------------------------------------------------')
        print('Classification Report: \n', report)
        print('Confusion Matrix: \n', conf_mx)

    # Create Performance Dataframe
    classifiers_df = pd.DataFrame({'Name':classfier_list, 'Accuracy (in %)': accuracy_scores,
                                   'Precision (in %)': precision_scores, 'Recall (in %)': recall_scores,
                                   'F1-Score (in %)': f1_scores})
    return classifiers_df

ml_classfiers_results_tfidf_gs = ml_classfiers_with_grid_search(x_train_tf, x_test_tf, y_train, y_test)

print('For models built on TF-IDF vectors and tuned using Grid Search:')
ml_classfiers_results_tfidf

"""You can observe that there is no difference in the model performance, even after using Grid Search method to fine tune the model. The maximum accuracy is 74.2% and F1-Score is 63%.

## MILESTONE 2
### Step 1 & 2: Design, train and test Neural networks, RNN or LSTM classifiers

### Using Neural Networks and Language Models

The vectorised form of the text is in 'Description Vector'. This is formed by performing TF-IDF vectorisation.
The data is prepared to be placed into the input layer of the neural network.
"""

# Setting the Parameters
X = pp_data['Description']
X_V = pp_data['Description_Vector']
Y = pp_data['Accident Level']

max_text_length = X.str.len().max()  # Maximum length of descriptions
vector_dim = len(X_V.iloc[0])  # Length of the first vector

tokenizer = Tokenizer()
tokenizer.fit_on_texts(X)
vocab_size = len(tokenizer.word_index) + 1

embedding_dim = 128
num_classes = 5        # Number of classes

"""##### SIMPLE NEURAL NETWORK MODEL"""

# Vector branch
vector_input = Input(shape=(vector_dim,), name='vector_input')
vector_dense1 = Dense(64, activation='relu')(vector_input)  # First Dense layer with 64 nodes
vector_dense2 = Dense(16, activation='relu')(vector_dense1)  # Second Dense layer with 16 nodes

# Output layer
output = Dense(num_classes, activation='softmax')(vector_dense2)  # Predict accident level

# Build the model
model_nn = Model(inputs=vector_input, outputs=output)
model_nn.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model_nn.summary()

"""##### RNN MODEL
Both TEXT and VECTORS have been added as Input branches, which are later concatenated as a single input
"""

# Text branch
text_input = Input(shape=(max_text_length,), name='text_input')
text_embedding = Embedding(vocab_size, embedding_dim, input_length=max_text_length)(text_input)
text_rnn = SimpleRNN(64)(text_embedding)  # Simple RNN layer

# Vector branch
vector_input = Input(shape=(vector_dim,), name='vector_input')
vector_dense = Dense(64, activation='relu')(vector_input)

# Concatenate branches
concatenated = concatenate([text_rnn, vector_dense])
# Additional Dense layer with 16 nodes
additional_dense = Dense(16, activation='relu')(concatenated)

# Output layer
output = Dense(num_classes, activation='softmax')(additional_dense)

# Build the model
model_rnn = Model(inputs=[text_input, vector_input], outputs=output)
model_rnn.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model_rnn.summary()

"""##### LSTM MODEL
Both TEXT and VECTORS have been added as Input branches, which are later concatenated as a single input
"""

# Text branch
text_input = Input(shape=(max_text_length,), name='text_input')
text_embedding = Embedding(vocab_size, embedding_dim, input_length=max_text_length)(text_input)
text_lstm = LSTM(128, return_sequences=True, dropout=0.2, recurrent_dropout=0.2)(text_embedding)
text_lstm = LSTM(64, dropout=0.3, recurrent_dropout=0.3)(text_lstm)

# Vector branch
vector_input = Input(shape=(vector_dim,), name='vector_input')
vector_dense = Dense(64, activation='relu')(vector_input)

# Concatenate branches
concatenated = concatenate([text_lstm, vector_dense])
# Additional Dense layer with 16 units
additional_dense = Dense(16, activation='relu')(concatenated)

# Output layer
output = Dense(num_classes, activation='softmax', kernel_regularizer=l2(0.01))(additional_dense)

# Build the model
model_lstm = Model(inputs=[text_input, vector_input], outputs=output)
optimizer = Adam(learning_rate=0.0005)
model_lstm.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model_lstm.summary()

"""##### BI-DIRECTIONAL LSTM MODEL"""

# Text branch
text_input = Input(shape=(max_text_length,), name='text_input')
text_embedding = Embedding(vocab_size, embedding_dim, input_length=max_text_length)(text_input)
text_bilstm = Bidirectional(LSTM(128, return_sequences=True, dropout=0.2, recurrent_dropout=0.2))(text_embedding)
text_bilstm = Bidirectional(LSTM(64, dropout=0.3, recurrent_dropout=0.3))(text_bilstm)

# Vector branch
vector_input = Input(shape=(vector_dim,), name='vector_input')
vector_dense = Dense(64, activation='relu')(vector_input)

# Concatenate branches
concatenated = concatenate([text_bilstm, vector_dense])
# Additional Dense layer with 16 units
additional_dense = Dense(16, activation='relu')(concatenated)

# Output layer
output = Dense(num_classes, activation='softmax', kernel_regularizer=l2(0.01))(additional_dense)

# Build the model
model_bilstm = Model(inputs=[text_input, vector_input], outputs=output)
model_bilstm.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model_bilstm.summary()

# Prepare text data
tokenizer = Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(X)
sequences = tokenizer.texts_to_sequences(X)
text_data = pad_sequences(sequences, maxlen=max_text_length)

# Prepare vector data
vector_data = np.array(X_V.tolist())

# Prepare labels
label_encoder = LabelEncoder()
labels = label_encoder.fit_transform(Y)

# Split data into training and test sets
X_train_text, X_test_text, X_train_vector, X_test_vector, y_train, y_test = train_test_split(
    text_data, vector_data, labels, test_size=0.2, random_state=1)

"""Training is done based on the compiled models, with the number of epochs chosen as 20, batch_size as 32 and validation_split as 0.1. The Plain NN model uses only the TF-IDF vectors, while the other models uses both a newly defined vectorisation and the TF-IDF vector as two parallel inputs that are concatenated in the second layer.

##### FUNCTION TO TRAIN AND EVALUATE THE MODELS
"""

def train_and_evaluate(model, X_train_text, X_train_vector, y_train, X_test_text, X_test_vector, y_test, is_nn_model=False):
    if is_nn_model:
        history = model.fit(X_train_vector, y_train, epochs=10, batch_size=32, validation_split=0.1)
        y_pred = model.predict(X_test_vector)
        loss, test_accuracy = model.evaluate(X_test_vector, y_test)
    else:
        history = model.fit([X_train_text, X_train_vector], y_train, epochs=20, batch_size=32, validation_split=0.1)
        y_pred = model.predict([X_test_text, X_test_vector])
        loss, test_accuracy = model.evaluate([X_test_text, X_test_vector], y_test)

    y_pred_labels = np.argmax(y_pred, axis=1)
    avg_training_accuracy = np.mean(history.history['accuracy'])
    precision_recall_report = classification_report(y_test, y_pred_labels, output_dict=True)
    precision = precision_recall_report['weighted avg']['precision']
    recall = precision_recall_report['weighted avg']['recall']

    return avg_training_accuracy, test_accuracy, precision, recall, y_pred_labels

# Training and evaluating each model
print('------------------ STARTING SIMPLE NEURAL NETWORK MODEL ------------------')
avg_train_acc_nn, test_acc_nn, precision_nn, recall_nn, predictions_nn = train_and_evaluate(model_nn, None, X_train_vector, y_train, None, X_test_vector, y_test, is_nn_model=True)
print('\n------------------ STARTING RNN MODEL ------------------')
avg_train_acc_rnn, test_acc_rnn, precision_rnn, recall_rnn, predictions_rnn = train_and_evaluate(model_rnn, X_train_text, X_train_vector, y_train, X_test_text, X_test_vector, y_test)
print('\n------------------ STARTING LSTM MODEL ------------------')
avg_train_acc_lstm, test_acc_lstm, precision_lstm, recall_lstm, predictions_lstm = train_and_evaluate(model_lstm, X_train_text, X_train_vector, y_train, X_test_text, X_test_vector, y_test)
print('\n------------------ STARTING BIDIRECTIONAL LSTM MODEL ------------------')
avg_train_acc_bilstm, test_acc_bilstm, precision_bilstm, recall_bilstm, predictions_bilstm = train_and_evaluate(model_bilstm, X_train_text, X_train_vector, y_train, X_test_text, X_test_vector, y_test)

# Compute and print confusion matrices
conf_matrix_nn = confusion_matrix(y_test, predictions_nn)
conf_matrix_rnn = confusion_matrix(y_test, predictions_rnn)
conf_matrix_lstm = confusion_matrix(y_test, predictions_lstm)
conf_matrix_bilstm = confusion_matrix(y_test, predictions_bilstm)

print("Confusion Matrix for SIMPLE NEURAL NETWORK Model:\n", conf_matrix_nn)
print("Confusion Matrix for RNN Model:\n", conf_matrix_rnn)
print("Confusion Matrix for LSTM Model:\n", conf_matrix_lstm)
print("Confusion Matrix for BIDIRECTIONAL LSTM Model:\n", conf_matrix_bilstm)

metrics_nn = [avg_train_acc_nn, test_acc_nn, precision_nn, recall_nn]
metrics_rnn = [avg_train_acc_rnn, test_acc_rnn, precision_rnn, recall_rnn]
metrics_lstm = [avg_train_acc_lstm, test_acc_lstm, precision_lstm, recall_lstm]
metrics_bilstm = [avg_train_acc_bilstm, test_acc_bilstm, precision_bilstm, recall_bilstm]

# Create a DataFrame
metrics_df = pd.DataFrame({
    'Model': ['NN', 'RNN', 'LSTM', 'BiLSTM'],
    'Avg Training Accuracy': [metrics_nn[0], metrics_rnn[0], metrics_lstm[0], metrics_bilstm[0]],
    'Test Accuracy': [metrics_nn[1], metrics_rnn[1], metrics_lstm[1], metrics_bilstm[1]],
    'Precision': [metrics_nn[2], metrics_rnn[2], metrics_lstm[2], metrics_bilstm[2]],
    'Recall': [metrics_nn[3], metrics_rnn[3], metrics_lstm[3], metrics_bilstm[3]]
})

metrics_df

"""The performance of the various models are presented in a dataframe.

<b>Obervations:</b><br/>
<ul>
    <li>The Training accuracy is highest but testing accuracy has dropped with RNN model.</li>
    <li>The Simple Neural Network model is performing the best for testing data but has lowest accuracy on Training data.</li>
    <li>As the trainig accuracy is dropping for models, the testing accuracy is increasing respectively.</li>
    <li>Precision is almost similar with all the models, with highest being in LSTM model.</li>
    <li>Compared to basic ML classifiers, Neural Network models are performing better on minority classes but it's significantly low, hence <b>we need to perform Data Augmentation to balance the dataset</b>.</li>

### Balancing the class distribution in the dataset using NLP Augmentation techniques
"""

X = pp_data['Description']
Y = pp_data['Accident Level']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

Y_train.value_counts()

minority_classes = ['II', 'III', 'IV', 'V']

"""##### SYNONYM AUGMENTATION"""

aug_syn = naw.SynonymAug(aug_src='wordnet', aug_p=0.1)

aug_syn_desc = []
aug_syn_lab = []

for i, label in enumerate(Y_train):
    if label in minority_classes:
        aug_syn_text = aug_syn.augment(X_train.iloc[i])
        aug_syn_desc.append(aug_syn_text)
        aug_syn_lab.append(label)

aug_syn_data = pd.DataFrame({'Description': aug_syn_desc, 'Accident_Level': aug_syn_lab})

X_train_aug_syn = pd.concat([X_train, aug_syn_data['Description']])
Y_train_aug_syn = pd.concat([Y_train, aug_syn_data['Accident_Level']])

Y_train_aug_syn.value_counts()

print('Shape of Dataset BEFORE Augmentation: (', X_train.shape[0], ',', Y_train.shape[0], ')')
print('Shape of Dataset AFTER Augmentation: (', X_train_aug_syn.shape[0], ',', Y_train_aug_syn.shape[0], ')')

"""##### CONTEXTUAL WORD EMBEDDINGS AUGMENTATION USING BERT GENERATIVE MODEL"""

aug_contextual = naw.ContextualWordEmbsAug(model_path='bert-base-uncased', action="substitute")

aug_contextual_desc = []
aug_contextual_lab = []

for i, label in enumerate(Y_train):
    if label in minority_classes:
        aug_contextual_text = aug_contextual.augment(X_train.iloc[i])
        aug_contextual_desc.append(aug_contextual_text)
        aug_contextual_lab.append(label)

aug_contextual_data = pd.DataFrame({'Description': aug_contextual_desc, 'Accident_Level': aug_contextual_lab})

# Combine the original training data with the augmented data
X_train_aug = pd.concat([X_train, aug_syn_data['Description'], aug_contextual_data['Description']])
Y_train_aug = pd.concat([Y_train, aug_syn_data['Accident_Level'], aug_contextual_data['Accident_Level']])

Y_train_aug.value_counts()

print('Shape of Training Dataset BEFORE Augmentation: ', X_train.shape)
print('Shape of Training Dataset AFTER Augmentation: ', X_train_aug.shape)
print('Shape of Testing Dataset BEFORE Augmentation: ', X_test.shape)

## Pie Chart for Class Distribution Before and After Augumentation

fig, axes = plt.subplots(1, 2, figsize=(12, 6))
axes[0].pie(Y_train.value_counts(), labels=Y_train.value_counts().keys(), autopct='%1.1f%%', startangle=140)
axes[0].set_title('Original Class Distribution')
axes[1].pie(Y_train_aug.value_counts(), labels=Y_train_aug.value_counts().keys(), autopct='%1.1f%%', startangle=140)
axes[1].set_title('Augmented Class Distribution')
plt.show()

"""### Performing Vectorization over the augmented training data and testing data

The Data Augmentation techniques used above are based on similar words and context of the accidents that have occurred in minority classes. TF-IDF Vectorization technique focus on the importance of terms in documents, which will not work with these Data Augmentation techniques. Hence, we have chosen <b>GLOVE EMBEDDINGS</b> as the Vecotrization technique, which is more effective for use cases involving semantic understanding, word similarity, and capturing relationships between words.
"""

# Load GloVe embeddings
glove = vocab.GloVe(name='6B', dim=50)

# Function to get word vector, handling out-of-vocabulary words
def get_word_vector(word):
    try:
        return glove[word]
    except KeyError:
        return torch.zeros_like(glove['the'])

# Create GloVe embeddings for the training data
X_train_aug_glove = []
for description in X_train_aug.index.astype(str):
    description_vector = [get_word_vector(word) for word in description.split()]
    mean_vector = torch.stack(description_vector).mean(dim=0).tolist()
    X_train_aug_glove.append(mean_vector)

# Create GloVe embeddings for the testing data
X_test_glove = []
for description in X_test:
    description_vector = [get_word_vector(word) for word in description.split()]
    mean_vector = torch.stack(description_vector).mean(dim=0).tolist()
    X_test_glove.append(mean_vector)

X_train_aug_glove_df = pd.DataFrame({'Description': X_train_aug, 'Description_Glove': X_train_aug_glove})
X_test_glove_df = pd.DataFrame({'Description': X_test, 'Description_Glove': X_test_glove})

X_train_aug_glove_df.head()

"""### Training above Neural Network models on augmented training data, and Evaluating them"""

# Concatenate training and testing datasets
X_glove_df = pd.concat([X_train_aug_glove_df, X_test_glove_df], ignore_index=True)

# Setting the Parameters
X = X_glove_df['Description']
X_V = X_glove_df['Description_Glove']
Y = pp_data['Accident Level']

max_text_length = X.str.len().max()  # Maximum length of descriptions
vector_dim = len(X_V.iloc[0])  # Length of the first vector

tokenizer = Tokenizer()
tokenizer.fit_on_texts(X)
vocab_size = len(tokenizer.word_index) + 1

embedding_dim = 128
num_classes = 5        # Number of classes

vector_dim

max_text_length

# Prepare training text data
tokenizer = Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(X_train_aug_glove_df['Description'])
sequences = tokenizer.texts_to_sequences(X_train_aug_glove_df['Description'])
X_train_text = pad_sequences(sequences, maxlen=max_text_length)

# Prepare testing text data
tokenizer = Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(X_test_glove_df['Description'])
sequences = tokenizer.texts_to_sequences(X_test_glove_df['Description'])
X_test_text = pad_sequences(sequences, maxlen=max_text_length)

# Prepare vector data
X_train_vector = np.array(X_train_aug_glove_df['Description_Glove'].tolist())
X_test_vector = np.array(X_test_glove_df['Description_Glove'].tolist())

# Prepare labels
label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(Y_train_aug)
y_test = label_encoder.fit_transform(Y_test)

len(X_train_text)

len(X_train_vector)

len(y_train)

"""##### TRAINING AND EVALUATING THE NEURAL NETWORKS"""

### The Simple NN model and RNN model are run through a simple grid search varying the learning rates.

from tensorflow.keras.models import clone_model
from tensorflow.keras.optimizers import Adam

## Gridsearch and Report for Simple NN
def perform_grid_search_nn(base_model, param_grid, X_train, y_train, X_test, y_test):
    results = []

    for params in param_grid:
        model = clone_model(base_model)
        optimizer = Adam(learning_rate=params['learning_rate'])
        model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

        avg_train_acc_nn, test_acc_nn, precision_nn, recall_nn, predictions_nn = train_and_evaluate(model_nn, None, X_train_vector, y_train, None, X_test_vector, y_test, is_nn_model=True)

        results.append({
            'params': params,
            'avg_train_accuracy': avg_train_acc_nn,
            'test_accuracy': test_acc_nn,
            'precision': precision_nn,
            'recall': recall_nn
        })

    return results

# Parameters
param_grid = [
    # Adam optimizer with different learning rates
    {'optimizer': 'adam', 'learning_rate': 0.001 },
    {'optimizer': 'adam', 'learning_rate': 0.0001 }
]

grid_search_results = perform_grid_search_nn(model_nn, param_grid, X_train_vector, y_train, X_test_vector, y_test)

# Dataframe the results
grid_search_results_df = pd.DataFrame(grid_search_results)
df_params = grid_search_results_df['params'].apply(pd.Series)
grid_search_results_df = pd.concat([grid_search_results_df.drop(['params'], axis=1), df_params], axis=1)
grid_search_results_df

## Gridsearch and Report for RNN
def perform_grid_search_rnn(base_model, param_grid, X_train_text, X_train_vector, y_train, X_test_text, X_test_vector, y_test):
    results = []

    for params in param_grid:
        model = clone_model(base_model)
        optimizer = Adam(learning_rate=params['learning_rate'])
        model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

        avg_train_acc_rnn, test_acc_rnn, precision_rnn, recall_rnn, predictions_rnn = train_and_evaluate(model_rnn, X_train_text, X_train_vector, y_train, X_test_text, X_test_vector, y_test)

        results.append({
            'params': params,
            'avg_train_accuracy': avg_train_acc_rnn,
            'test_accuracy': test_acc_rnn,
            'precision': precision_rnn,
            'recall': recall_rnn
        })

    return results

# Parameters
param_grid = [
    # Adam optimizer with different learning rates
    {'optimizer': 'adam', 'learning_rate': 0.001 },
    {'optimizer': 'adam', 'learning_rate': 0.0001 }
]

grid_search_results = perform_grid_search_rnn(model_rnn, param_grid, X_train_text, X_train_vector, y_train, X_test_text, X_test_vector, y_test)

# Dataframe the results
grid_search_results_df = pd.DataFrame(grid_search_results)
df_params = grid_search_results_df['params'].apply(pd.Series)
grid_search_results_df = pd.concat([grid_search_results_df.drop(['params'], axis=1), df_params], axis=1)
grid_search_results_df

## Gridsearch and Report for RNN
def perform_grid_search_rnn(base_model, param_grid, X_train_text, X_train_vector, y_train, X_test_text, X_test_vector, y_test):
    results = []

    for params in param_grid:
        model = clone_model(base_model)
        optimizer = Adam(learning_rate=params['learning_rate'])
        model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

        avg_train_acc_rnn, test_acc_rnn, precision_rnn, recall_rnn, predictions_rnn = train_and_evaluate(model_rnn, X_train_text, X_train_vector, y_train, X_test_text, X_test_vector, y_test)

        results.append({
            'params': params,
            'avg_train_accuracy': avg_train_acc_rnn,
            'test_accuracy': test_acc_rnn,
            'precision': precision_rnn,
            'recall': recall_rnn
        })

    return results

# Parameters
param_grid = [
    # Adam optimizer with different learning rates
    {'optimizer': 'adam', 'learning_rate': 0.001 },
    {'optimizer': 'adam', 'learning_rate': 0.0001 }
]

grid_search_results = perform_grid_search_rnn(model_rnn, param_grid, X_train_text, X_train_vector, y_train, X_test_text, X_test_vector, y_test)

# Dataframe the results
grid_search_results_df = pd.DataFrame(grid_search_results)
df_params = grid_search_results_df['params'].apply(pd.Series)
grid_search_results_df = pd.concat([grid_search_results_df.drop(['params'], axis=1), df_params], axis=1)
grid_search_results_df

print('------------------ STARTING SIMPLE NEURAL NETWORK MODEL ------------------')
avg_train_acc_nn, test_acc_nn, precision_nn, recall_nn, predictions_nn = train_and_evaluate(model_nn, None, X_train_vector, y_train, None, X_test_vector, y_test, is_nn_model=True)
print('\n------------------ STARTING RNN MODEL ------------------')
avg_train_acc_rnn, test_acc_rnn, precision_rnn, recall_rnn, predictions_rnn = train_and_evaluate(model_rnn, X_train_text, X_train_vector, y_train, X_test_text, X_test_vector, y_test)
print('\n------------------ STARTING LSTM MODEL ------------------')
avg_train_acc_lstm, test_acc_lstm, precision_lstm, recall_lstm, predictions_lstm = train_and_evaluate(model_lstm, X_train_text, X_train_vector, y_train, X_test_text, X_test_vector, y_test)
print('\n------------------ STARTING BIDIRECTIONAL LSTM MODEL ------------------')
avg_train_acc_bilstm, test_acc_bilstm, precision_bilstm, recall_bilstm, predictions_bilstm = train_and_evaluate(model_bilstm, X_train_text, X_train_vector, y_train, X_test_text, X_test_vector, y_test)

# Compute and print confusion matrices
conf_matrix_nn = confusion_matrix(y_test, predictions_nn)
conf_matrix_rnn = confusion_matrix(y_test, predictions_rnn)
conf_matrix_lstm = confusion_matrix(y_test, predictions_lstm)
conf_matrix_bilstm = confusion_matrix(y_test, predictions_bilstm)

print("Confusion Matrix for SIMPLE NEURAL NETWORK Model:\n", conf_matrix_nn)
print("Confusion Matrix for RNN Model:\n", conf_matrix_rnn)
print("Confusion Matrix for LSTM Model:\n", conf_matrix_lstm)
print("Confusion Matrix for BIDIRECTIONAL LSTM Model:\n", conf_matrix_bilstm)

metrics_nn = [avg_train_acc_nn, test_acc_nn, precision_nn, recall_nn]
metrics_rnn = [avg_train_acc_rnn, test_acc_rnn, precision_rnn, recall_rnn]
metrics_lstm = [avg_train_acc_lstm, test_acc_lstm, precision_lstm, recall_lstm]
metrics_bilstm = [avg_train_acc_bilstm, test_acc_bilstm, precision_bilstm, recall_bilstm]

# Create a DataFrame
metrics_df = pd.DataFrame({
    'Model': ['NN', 'RNN', 'LSTM', 'BiLSTM'],
    'Avg Training Accuracy': [metrics_nn[0], metrics_rnn[0], metrics_lstm[0], metrics_bilstm[0]],
    'Test Accuracy': [metrics_nn[1], metrics_rnn[1], metrics_lstm[1], metrics_bilstm[1]],
    'Precision': [metrics_nn[2], metrics_rnn[2], metrics_lstm[2], metrics_bilstm[2]],
    'Recall': [metrics_nn[3], metrics_rnn[3], metrics_lstm[3], metrics_bilstm[3]]
})

metrics_df

"""## Use Nested Classification Process using GloVe Embeddings and BiLSTM."""

# Convert labels to binary: 1 for Class 1, 0 for Not Class 1
y_train_binary = np.where(y_train == 0, 0, 1)
y_test_binary = np.where(y_test == 0, 0, 1)

# Define and train the first level classifier
model_bilstm_2 = clone_model(model_bilstm)
model_bilstm_2.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
avg_train_acc_first_level, test_acc_first_level, precision_first_level, recall_first_level, predictions_first_level = train_and_evaluate(model_bilstm_2, X_train_text, X_train_vector, y_train_binary, X_test_text, X_test_vector, y_test_binary)

conf_matrix_first_level = confusion_matrix(y_test_binary, predictions_first_level)

# Compute and print the classification report which includes precision, recall, and F1-score
class_report_first_level = classification_report(y_test_binary, predictions_first_level)

print("First Level Classifier Performance:")
print(f"Average Training Accuracy: {avg_train_acc_first_level}")
print(f"Test Accuracy: {test_acc_first_level}")
print(f"Precision: {precision_first_level}")
print(f"Recall: {recall_first_level}")
print("Classification Report:\n", class_report_first_level)
print("Confusion Matrix:\n", conf_matrix_first_level)

# Filter data for classes 2, 3, 4, 5
mask_train = y_train != 0
mask_test = y_test != 0

X_train_text_second_level = X_train_text[mask_train]
X_train_vector_second_level = X_train_vector[mask_train]
y_train_second_level = y_train[mask_train]

X_test_text_second_level = X_test_text[mask_test]
X_test_vector_second_level = X_test_vector[mask_test]
y_test_second_level = y_test[mask_test]

model_bilstm_3 = clone_model(model_bilstm)
model_bilstm_3.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
avg_train_acc_second_level, test_acc_second_level, precision_second_level, recall_second_level, predictions_second_level = train_and_evaluate(
    model_bilstm_3, X_train_text_second_level, X_train_vector_second_level, y_train_second_level, X_test_text_second_level, X_test_vector_second_level, y_test_second_level)

conf_matrix_second_level = confusion_matrix(y_test_second_level, predictions_second_level)

# Compute and print the classification report which includes precision, recall, and F1-score
class_report_second_level = classification_report(y_test_second_level, predictions_second_level)

print("Second Level Classifier Performance:")
print(f"Average Training Accuracy: {avg_train_acc_second_level}")
print(f"Test Accuracy: {test_acc_second_level}")
print(f"Precision: {precision_second_level}")
print(f"Recall: {recall_second_level}")
print("Classification Report:\n", class_report_second_level)
print("Confusion Matrix:\n", conf_matrix_second_level)

predictions_level_1 = model_bilstm_2.predict([X_test_text, X_test_vector])
predictions_level_1 = np.argmax(predictions_level_1, axis=1)
predictions_level_2 = model_bilstm_3.predict([X_test_text_second_level, X_test_vector_second_level])
predictions_level_2 = np.argmax(predictions_level_2, axis=1)

combined_predictions = np.copy(predictions_level_1.flatten())
combined_predictions[mask_test] = predictions_level_2.flatten()

print("Combined Classifier Performance:")
print(classification_report(y_test, combined_predictions))
conf_matrix_combined = confusion_matrix(y_test, combined_predictions)
print("Confusion Matrix:\n", conf_matrix_combined)

import pickle
best_classifier = model_bilstm
with open('best_classifier.pkl', 'wb') as file:
    pickle.dump(best_classifier, file)
print("Model saved successfully.")


with open('best_classifier.pkl', 'rb') as file:
    loaded_classifier = pickle.load(file)